name: Build ANTs for macOS ARM

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ANTs (macOS ARM)
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install cmake ninja
        which cmake
        which ninja
        cmake --version
        ninja --version

    - name: Configure ANTs
      run: |
        cd ${{ github.workspace }}
        mkdir -p ANTs && cd ANTs
        git clone https://github.com/ANTsX/ANTs.git source
        mkdir build && cd build
        cmake ../source \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/ANTs/install
          -DCMAKE_OSX_ARCHITECTURES=arm64 \
          -DBUILD_TESTING=OFF \
          -DBUILD_SHARED_LIBS=OFF \
          -DBUILD_EXAMPLES=OFF \
          -G Ninja

    - name: Build
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        cd build
        cmake --build . --config Release --parallel

    - name: Install
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        cd build/ANTS-build
        cmake --install .

    - name: Get ANTs version
      id: version
      run: |
        cd ANTs/source
        echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT

    - name: Pack
      run: |
        cd ${{ github.workspace }}/ANTs
        tar -czvf ANTs_package_macos_arm_${{ steps.version.outputs.version }}.tar.gz install/

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: ANTs-macos-arm-${{ steps.version.outputs.version }}
        path: ${{ github.workspace }}/ANTs/ANTs_package_macos_arm_${{ steps.version.outputs.version }}.tar.gz
        if-no-files-found: error

    - name: Cleanup
      if: always()
      run: rm -rf ${{ github.workspace }}/ANTs/