name: Build ANTs for Ubuntu

on:
  # Allows to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1

    - name: Install cmake
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build cmake
        ninja --version
        cmake --version
        gcc --version

    - name: Build ANTs
      run: |
        cd ${{github.workspace}}
        mkdir ANTs
        cd ANTs
        git clone https://github.com/ANTsX/ANTs.git source
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/ANTs/install ../source
        make -j4
        cd ANTS-build
        make install
        cp -R ${{github.workspace}}/ANTs/source/Scripts ${{github.workspace}}/ANTs/install/

    - name: Pack
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        cd ANTs/
        tar -czvf ${{github.workspace}}/ANTs/ANTs_package_ubuntu.tar.gz install/

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: ${{github.workspace}}/ANTs/ANTs*
        if-no-files-found: error

    - name: Cleanup
      if: always()
      run: |
        rm -rf ${{github.workspace}}/ANTs/