name: Build ANTs for macOS ARM

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ANTs (macOS ARM)
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install cmake ninja
        which cmake
        which ninja
        cmake --version
        ninja --version

    - name: Configure ANTs
      working-directory: ${{ github.workspace }}
      run: |
        mkdir -p ANTs && cd ANTs
        git clone https://github.com/ANTsX/ANTs.git source
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/ANTs/install -G Ninja ../source

    - name: Build
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        cd ANTs/build
        cmake --build . --config Release --parallel

    - name: Install
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        cd ANTs/build/ANTS-build
        cmake --install .

    - name: Get ANTs version
      id: version
      run: |
        cd ANTs/source
        echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT

    - name: Pack
      run: |
        cd ${{ github.workspace }}/ANTs
        tar -czvf ANTs_${{ steps.version.outputs.version }}_macos_arm.tar.gz install/

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: ANTs-macos-arm-${{ steps.version.outputs.version }}
        path: ${{ github.workspace }}/ANTs/ANTs_${{ steps.version.outputs.version }}_macos_arm.tar.gz
        if-no-files-found: error

    - name: Cleanup
      if: always()
      run: rm -rf ${{ github.workspace }}/ANTs/